name: null
original_model: False
epochs: [5,10,20,30,50,80,100,120,150]
batch_size: 1
activity_dropout_prob: 0.0
activity_dropout_train: 0.2
hidden_layer_size: 8
latent_overshoot: 6
prediction_overshoot: 0
latent_predictor_type: transformer
learn_latent_magnitude: False
movement_inertia: 0.0
latent_evidence_weight: 1.0
leniency: 0
lookahead_steps: 1
query_step: 1
# query_types: ['object','activity','both']
query_types: []
query_thresh: 0.5
only_confused_queries: True
query_negative_at_all_steps: False
query_trust: 0.8
query_usefullness_thresh:
  information_gain: [0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.3, 0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 20.0, 50.0]
consistency_thresholds: [10]
aux_loss_weight: 0.0
c_len: 16
addtnl_time_context: False
latent_regularization: null
latent_similarity_weight: 1
loss_object_cross: True
loss_activity_cross: True
loss_object_combined: True
loss_activity_combined: True
loss_latent_similarity: True
loss_latent_pred: True
loss_object_pred: True
loss_activity_pred: True
